### ISSUE TITLE
Overlay does not open

### ISSUE THREAD

**Issue by hhubik** [mainawycliffe/ng-cdk-overlay-demo#2]
Greetings,

I am trying to implement your Overlay Service in my project.  Unfortunately, I am unable to open the overlay from my button click event handler.  Most likely, I missed a step in your instructions.  If you have time, I would appreciate if you could look over my code and let me know what I am doing wrong.  

My code is [here](https://github.com/vis/poltrack/tree/overlay-service).

Feel free to leave any suggestions you may have [here](https://github.com/vis/poltrack/issues/30).

Thanks!

**Comment by mainawycliffe** [comment]
Greetings,

I would love to help, can you send me the lint to the component where you were trying to implement this.

**Comment by hhubik** [comment]
I think I know what the problem is. Though I don't know yet how to fix it.  Your demo code uses `bulma`.  My app uses `bootstrap` (without jquery) and `Angular Material`.  

After commenting out 
```
      panelClass: ['modal', 'is-active'],
      backdropClass: 'modal-background' // ,
```
I actually see the overlay background pop up (and go away if I click on it).  I don't yet see the expected content, which at the moment is just  a string.

The component where I am using the Overlay Service is called [ProviderSearchByActionViewComponent](https://github.com/vis/poltrack/blob/overlay-service/src/app/pt-report/components/provider-search-by-action-view.component.ts).

See the `onShowFullInfoDocButtonClicked` function at the end of the file.

Though the actual opening of the overlay happens in [PtReportConfigurationService](https://github.com/vis/poltrack/blob/overlay-service/src/app/pt-report/pt-report-configuration.service.ts).

**Comment by mainawycliffe** [comment]
Yeah, bootstrap modal css class work a little bit different from bulma css. I can't recall of my head, but let me have a look at how I used to do this.

**Comment by hhubik** [comment]
Thanks, but I have just managed to solve this by using the Angular Material `Dialog` component.  It appears to do what I need out-of-the-box. I still appreciate your overlay project.  It helped me better understand how the overlay works, and that is helpful as the `Dialog` is based on the `Overlay`.
