### ISSUE TITLE
PortalInjector is depreciated 

### ISSUE THREAD

**Issue by axmad22** [mainawycliffe/ng-cdk-overlay-demo#4]
Thanks for this nice library but in _angular version 10.1.2_ the **PortalInjector** is depreciated  I tried fixing it using this method in the _overlay.service.ts_ 

``` js
createInjector(ref: MyOverlayRef, inj: Injector) {
    return Injector.create({parent: this.injector, providers: [{provide: MyOverlayRef, useValue: ref}]});
  }
```

It compiles but in the _overlay.component.html_ the ***ngSwitchCase** directives are not recognized apparently dynamically creating component does not include **CommonModule** from _@angular/common_. I don't know what to try next any ideas on how to update it

**Comment by TimToplak** [comment]
Did you find the solution?

**Comment by TimToplak** [comment]
This works for me: 
```  
public getInjector(ref: MyOverlayRef, inj: Injector): Injector {
    return Injector.create({
      parent: inj,
      providers: [
        {provide: MyOverlayRef, useValue: ref},
      ],
    });
  }
